[cursor]
blink_interval = 550
unfocused_hollow = true

[cursor.style]
blinking = "On"
shape = "Block"

[font]
size = 14

[font.bold]
family = "JetBrainsMono Nerd Font"

[font.bold_italic]
family = "JetBrainsMono Nerd Font"

[font.italic]
family = "JetBrainsMono Nerd Font"

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[selection]
save_to_clipboard = false

[window]
decorations = "none"
dynamic_title = true
opacity = 1.0

[window.padding]
x = 15
y = 15

[general]
live_config_reload = true

import = [
   "~/.config/alacritty/theme.toml"
]
